spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: ture
  cache:
    jcache:
      config: classpath:ehcache.xml

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    api-docs:
      path: /api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug

kakaoapi:
  url: https://dapi.kakao.com/v2/search/blog
  token: KakaoAK bd9fc2602bfd3027fbdaefb3fdac8093

naverapi:
  url: https://openapi.naver.com/v1/search/blog.json
  id: D_qiya88rR3EqiUxNZFx
  secret: bAKrwztRHM


